name: Build solution and installer

on: 
  push:
    branches:
      - 'master'
      - 'installer'
    tags-ignore:
      - '*.*'

jobs:
  buildSolution:
    name: Build Speckle AutoCAD plugin
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: list files
      run: dir /s /b
