name: Build solution and installer

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - '*.*'


jobs:
  buildSolution:
    name: Build Speckle AutoCAD plugin
    runs-on: windows-latest
    steps:
    - name: Calculate tag version
      id: calculateTagVersion
      run: |
        $tag = "1.0.0.$($env:GITHUB_RUN_NUMBER%65536)"
        echo "::set-output name=tag::$tag"
        
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'  

    - name: Install third party dependencies
      working-directory: SpeckleUiApp
      run: npm ci 
      
    - name: build Speckle UI App
      working-directory: SpeckleUiApp
      run: npm run build 
      
    - name: Install the latest version of nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Analytics CLI - Restore NuGets
      run: dotnet restore
      working-directory: Analytics

    - name: NuGet restore
      run: nuget restore SpeckleAutoCAD.sln
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run msbuild command in Release
      run: msbuild speckleautocad.sln -restore -p:Configuration=Release57 -p:platform=x64

    - name: Analytics CLI - Compile CLI
      run: dotnet build --configuration Release --runtime win-x64
      working-directory: Analytics
      
    - name: Install Azure Key Vault signtool
      run: dotnet tool install --global AzureSignTool --version 2.0.17
      
    - name: Create List of dlls to be signed
      shell: powershell
      run: |
        ls -r Release\SpeckleAutoCAD2020\Contents\Win64\2020\SpeckleAutoCAD*.dll | select  -ExpandProperty FullName | set-content dlls.txt
        ls -r Release\SpeckleAutoCAD2021\Contents\Win64\2021\SpeckleAutoCAD*.dll | select  -ExpandProperty FullName | add-content dlls.txt
      
    # https://github.com/vcsjones/AzureSignTool
    - name: Sign Dlls
      shell: powershell
      run: |
        AzureSignTool sign `
          --description-url "https://speckle.arup.com" `
          --azure-key-vault-url "https://oasysevkv.vault.azure.net/" `
          --azure-key-vault-client-id "${{ secrets.AZURE_CLIENT_ID }}" `
          --azure-key-vault-client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" `
          --azure-key-vault-certificate "OasysCodeSigning" `
          --timestamp-rfc3161 "http://timestamp.digicert.com" `
          --verbose `
          --input-file-list ${{ github.workspace }}\dlls.txt

    - name: Create installer
      run: iscc /DAppVersion="${{ steps.calculateTagVersion.outputs.tag }}" "/Ssigntool=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool.exe sign /f ""${{ steps.decodePfxCert.outputs.pfxPath }}"" /p ""${{ secrets.PFX_CERT_PASSWORD }}"" /t http://timestamp.comodoca.com $f" Installer/InstallerScript.iss
      shell: cmd
      env:
        ENABLE_TELEMETRY_DOMAIN: ${{ secrets.ENABLE_TELEMETRY_DOMAIN }}
        
    - name: Get Name of exe file
      id: listName
      working-directory: Installer\Build
      shell: powershell
      run: |
        $filename = (ls *.exe).Name
        echo "::set-output name=filename::$filename"
    
    # https://github.com/vcsjones/AzureSignTool
    - name: Sign Installer
      shell: powershell
      run: |
        AzureSignTool sign `
          --description-url "https://speckle.arup.com" `
          --azure-key-vault-url "https://oasysevkv.vault.azure.net/" `
          --azure-key-vault-client-id "${{ secrets.AZURE_CLIENT_ID }}" `
          --azure-key-vault-client-secret "${{ secrets.AZURE_CLIENT_SECRET }}" `
          --azure-key-vault-certificate "OasysCodeSigning" `
          --timestamp-rfc3161 "http://timestamp.digicert.com" `
          --verbose `
          ${{ github.workspace }}\Installer\Build\${{ steps.listName.outputs.filename }} 
  
    - name: Upload build files
      uses: actions/upload-artifact@v2-preview
      with:
        name: SpeckleAutoCAD-${{ steps.calculateTagVersion.outputs.tag }}
        path: 'Installer/Build/SpeckleAutoCADInstaller.exe'
  
    - name: Create release
      if: github.ref == 'refs/heads/master'
      id: createRelease
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ steps.calculateTagVersion.outputs.tag }}
        release_name: Speckle AutoCAD Installer ${{ steps.calculateTagVersion.outputs.tag }} Alpha
        body: |
          Automated release of Speckle AutoCAD Installer
        draft: false
        prerelease: true

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/master'
      id: uploadReleaseAsset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.createRelease.outputs.upload_url }}  
        asset_path: Installer/Build/SpeckleAutoCADInstaller.exe
        asset_name: SpeckleAutoCADInstaller.exe
        asset_content_type: application/vnd.microsoft.portable-executable
